CHANGE MASTER TO
  MASTER_HOST='testifydb02fl',
  MASTER_USER='master',
  MASTER_PASSWORD='6Ex920URZ0e3YzKG',
  MASTER_LOG_FILE='mysql-bin.000002',
  MASTER_LOG_POS=342;

START SLAVE;


CHANGE MASTER TO
  MASTER_HOST='testifydb02fl',
  MASTER_USER='slave_to_master',
  MASTER_PASSWORD='your_password',
  MASTER_LOG_FILE='mysql-bin.000001',
  MASTER_LOG_POS=XXX;
START SLAVE;
